/*
 * Fipe API
 *
 * API de Consulta Tabela FIPE fornece preços médios de veículos no mercado nacional. Atualizada mensalmente com dados extraidos da tabela FIPE <p>Essa API Fipe utiliza banco de dados próprio, onde todas as requisições acontecem internamente, sem sobrecarregar o Web Service da Fipe, evitando assim bloqueios por múltiplos acessos.<p/> <p>A API está online desde 2015 e totalmente gratuíta. Gostaria que ele continuasse gratuíta? O que acha de me pagar uma cerveja? 🍺<p/> [![Make a donation](https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUPMYWH6XAC5G) <br><br> <h3>Available SDKs</h3> [Fipe Go SDK](https://pkg.go.dev/github.com/parallelum/fipe-go) <br> [Fipe .NetCore Nuget](https://www.nuget.org/packages/Br.Com.Parallelum.Fipe/)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: deividfortuna@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Br.Com.Parallelum.Fipe.Client;
using Br.Com.Parallelum.Fipe.Model;

namespace Br.Com.Parallelum.Fipe.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFipeApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Brands by type
        /// </summary>
        /// <remarks>
        /// Returns brands for the type of vehicle
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <returns>List&lt;NamedCode&gt;</returns>
        List<NamedCode> GetBrandsByType(VehiclesType vehicleType);

        /// <summary>
        /// Brands by type
        /// </summary>
        /// <remarks>
        /// Returns brands for the type of vehicle
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <returns>ApiResponse of List&lt;NamedCode&gt;</returns>
        ApiResponse<List<NamedCode>> GetBrandsByTypeWithHttpInfo(VehiclesType vehicleType);
        /// <summary>
        /// Fipe info
        /// </summary>
        /// <remarks>
        /// Returns the Fipe information for the vehicle (price estimation)
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="yearId">Year for the vehicle</param>
        /// <param name="reference">Month reference code (optional)</param>
        /// <returns>FipeResult</returns>
        FipeResult GetFipeInfo(VehiclesType vehicleType, int brandId, int modelId, string yearId, int? reference = default(int?));

        /// <summary>
        /// Fipe info
        /// </summary>
        /// <remarks>
        /// Returns the Fipe information for the vehicle (price estimation)
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="yearId">Year for the vehicle</param>
        /// <param name="reference">Month reference code (optional)</param>
        /// <returns>ApiResponse of FipeResult</returns>
        ApiResponse<FipeResult> GetFipeInfoWithHttpInfo(VehiclesType vehicleType, int brandId, int modelId, string yearId, int? reference = default(int?));
        /// <summary>
        /// Models by brand
        /// </summary>
        /// <remarks>
        /// Returns models for the brand
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <returns>List&lt;NamedCode&gt;</returns>
        List<NamedCode> GetModelsByBrand(VehiclesType vehicleType, int brandId);

        /// <summary>
        /// Models by brand
        /// </summary>
        /// <remarks>
        /// Returns models for the brand
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <returns>ApiResponse of List&lt;NamedCode&gt;</returns>
        ApiResponse<List<NamedCode>> GetModelsByBrandWithHttpInfo(VehiclesType vehicleType, int brandId);
        /// <summary>
        /// Fipe month references
        /// </summary>
        /// <remarks>
        /// Returns months and codes reference from Fipe
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Reference&gt;</returns>
        List<Reference> GetReferences();

        /// <summary>
        /// Fipe month references
        /// </summary>
        /// <remarks>
        /// Returns months and codes reference from Fipe
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Reference&gt;</returns>
        ApiResponse<List<Reference>> GetReferencesWithHttpInfo();
        /// <summary>
        /// Years for model
        /// </summary>
        /// <remarks>
        /// Returns years for the specific model
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <returns>List&lt;NamedCode&gt;</returns>
        List<NamedCode> GetYearByModel(VehiclesType vehicleType, int brandId, int modelId);

        /// <summary>
        /// Years for model
        /// </summary>
        /// <remarks>
        /// Returns years for the specific model
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <returns>ApiResponse of List&lt;NamedCode&gt;</returns>
        ApiResponse<List<NamedCode>> GetYearByModelWithHttpInfo(VehiclesType vehicleType, int brandId, int modelId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFipeApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Brands by type
        /// </summary>
        /// <remarks>
        /// Returns brands for the type of vehicle
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NamedCode&gt;</returns>
        System.Threading.Tasks.Task<List<NamedCode>> GetBrandsByTypeAsync(VehiclesType vehicleType, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Brands by type
        /// </summary>
        /// <remarks>
        /// Returns brands for the type of vehicle
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NamedCode&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<NamedCode>>> GetBrandsByTypeWithHttpInfoAsync(VehiclesType vehicleType, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Fipe info
        /// </summary>
        /// <remarks>
        /// Returns the Fipe information for the vehicle (price estimation)
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="yearId">Year for the vehicle</param>
        /// <param name="reference">Month reference code (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FipeResult</returns>
        System.Threading.Tasks.Task<FipeResult> GetFipeInfoAsync(VehiclesType vehicleType, int brandId, int modelId, string yearId, int? reference = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Fipe info
        /// </summary>
        /// <remarks>
        /// Returns the Fipe information for the vehicle (price estimation)
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="yearId">Year for the vehicle</param>
        /// <param name="reference">Month reference code (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FipeResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<FipeResult>> GetFipeInfoWithHttpInfoAsync(VehiclesType vehicleType, int brandId, int modelId, string yearId, int? reference = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Models by brand
        /// </summary>
        /// <remarks>
        /// Returns models for the brand
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NamedCode&gt;</returns>
        System.Threading.Tasks.Task<List<NamedCode>> GetModelsByBrandAsync(VehiclesType vehicleType, int brandId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Models by brand
        /// </summary>
        /// <remarks>
        /// Returns models for the brand
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NamedCode&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<NamedCode>>> GetModelsByBrandWithHttpInfoAsync(VehiclesType vehicleType, int brandId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Fipe month references
        /// </summary>
        /// <remarks>
        /// Returns months and codes reference from Fipe
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Reference&gt;</returns>
        System.Threading.Tasks.Task<List<Reference>> GetReferencesAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Fipe month references
        /// </summary>
        /// <remarks>
        /// Returns months and codes reference from Fipe
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Reference&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Reference>>> GetReferencesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Years for model
        /// </summary>
        /// <remarks>
        /// Returns years for the specific model
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NamedCode&gt;</returns>
        System.Threading.Tasks.Task<List<NamedCode>> GetYearByModelAsync(VehiclesType vehicleType, int brandId, int modelId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Years for model
        /// </summary>
        /// <remarks>
        /// Returns years for the specific model
        /// </remarks>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NamedCode&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<NamedCode>>> GetYearByModelWithHttpInfoAsync(VehiclesType vehicleType, int brandId, int modelId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFipeApi : IFipeApiSync, IFipeApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FipeApi : IFipeApi
    {
        private Br.Com.Parallelum.Fipe.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FipeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FipeApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FipeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FipeApi(string basePath)
        {
            this.Configuration = Br.Com.Parallelum.Fipe.Client.Configuration.MergeConfigurations(
                Br.Com.Parallelum.Fipe.Client.GlobalConfiguration.Instance,
                new Br.Com.Parallelum.Fipe.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Br.Com.Parallelum.Fipe.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Br.Com.Parallelum.Fipe.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Br.Com.Parallelum.Fipe.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FipeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FipeApi(Br.Com.Parallelum.Fipe.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Br.Com.Parallelum.Fipe.Client.Configuration.MergeConfigurations(
                Br.Com.Parallelum.Fipe.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Br.Com.Parallelum.Fipe.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Br.Com.Parallelum.Fipe.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Br.Com.Parallelum.Fipe.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FipeApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public FipeApi(Br.Com.Parallelum.Fipe.Client.ISynchronousClient client, Br.Com.Parallelum.Fipe.Client.IAsynchronousClient asyncClient, Br.Com.Parallelum.Fipe.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Br.Com.Parallelum.Fipe.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Br.Com.Parallelum.Fipe.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Br.Com.Parallelum.Fipe.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Br.Com.Parallelum.Fipe.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Br.Com.Parallelum.Fipe.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Brands by type Returns brands for the type of vehicle
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <returns>List&lt;NamedCode&gt;</returns>
        public List<NamedCode> GetBrandsByType(VehiclesType vehicleType)
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> localVarResponse = GetBrandsByTypeWithHttpInfo(vehicleType);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Brands by type Returns brands for the type of vehicle
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <returns>ApiResponse of List&lt;NamedCode&gt;</returns>
        public Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> GetBrandsByTypeWithHttpInfo(VehiclesType vehicleType)
        {
            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("vehicleType", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(vehicleType)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<NamedCode>>("/{vehicleType}/brands", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetBrandsByType", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Brands by type Returns brands for the type of vehicle
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NamedCode&gt;</returns>
        public async System.Threading.Tasks.Task<List<NamedCode>> GetBrandsByTypeAsync(VehiclesType vehicleType, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> localVarResponse = await GetBrandsByTypeWithHttpInfoAsync(vehicleType, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Brands by type Returns brands for the type of vehicle
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NamedCode&gt;)</returns>
        public async System.Threading.Tasks.Task<Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>>> GetBrandsByTypeWithHttpInfoAsync(VehiclesType vehicleType, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("vehicleType", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(vehicleType)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<NamedCode>>("/{vehicleType}/brands", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetBrandsByType", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fipe info Returns the Fipe information for the vehicle (price estimation)
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="yearId">Year for the vehicle</param>
        /// <param name="reference">Month reference code (optional)</param>
        /// <returns>FipeResult</returns>
        public FipeResult GetFipeInfo(VehiclesType vehicleType, int brandId, int modelId, string yearId, int? reference = default(int?))
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<FipeResult> localVarResponse = GetFipeInfoWithHttpInfo(vehicleType, brandId, modelId, yearId, reference);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fipe info Returns the Fipe information for the vehicle (price estimation)
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="yearId">Year for the vehicle</param>
        /// <param name="reference">Month reference code (optional)</param>
        /// <returns>ApiResponse of FipeResult</returns>
        public Br.Com.Parallelum.Fipe.Client.ApiResponse<FipeResult> GetFipeInfoWithHttpInfo(VehiclesType vehicleType, int brandId, int modelId, string yearId, int? reference = default(int?))
        {
            // verify the required parameter 'yearId' is set
            if (yearId == null)
                throw new Br.Com.Parallelum.Fipe.Client.ApiException(400, "Missing required parameter 'yearId' when calling FipeApi->GetFipeInfo");

            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("vehicleType", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(vehicleType)); // path parameter
            localVarRequestOptions.PathParameters.Add("brandId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(brandId)); // path parameter
            localVarRequestOptions.PathParameters.Add("modelId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(modelId)); // path parameter
            localVarRequestOptions.PathParameters.Add("yearId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(yearId)); // path parameter
            if (reference != null)
            {
                localVarRequestOptions.QueryParameters.Add(Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToMultiMap("", "reference", reference));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<FipeResult>("/{vehicleType}/brands/{brandId}/models/{modelId}/years/{yearId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFipeInfo", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fipe info Returns the Fipe information for the vehicle (price estimation)
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="yearId">Year for the vehicle</param>
        /// <param name="reference">Month reference code (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FipeResult</returns>
        public async System.Threading.Tasks.Task<FipeResult> GetFipeInfoAsync(VehiclesType vehicleType, int brandId, int modelId, string yearId, int? reference = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<FipeResult> localVarResponse = await GetFipeInfoWithHttpInfoAsync(vehicleType, brandId, modelId, yearId, reference, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fipe info Returns the Fipe information for the vehicle (price estimation)
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="yearId">Year for the vehicle</param>
        /// <param name="reference">Month reference code (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FipeResult)</returns>
        public async System.Threading.Tasks.Task<Br.Com.Parallelum.Fipe.Client.ApiResponse<FipeResult>> GetFipeInfoWithHttpInfoAsync(VehiclesType vehicleType, int brandId, int modelId, string yearId, int? reference = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'yearId' is set
            if (yearId == null)
                throw new Br.Com.Parallelum.Fipe.Client.ApiException(400, "Missing required parameter 'yearId' when calling FipeApi->GetFipeInfo");


            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("vehicleType", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(vehicleType)); // path parameter
            localVarRequestOptions.PathParameters.Add("brandId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(brandId)); // path parameter
            localVarRequestOptions.PathParameters.Add("modelId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(modelId)); // path parameter
            localVarRequestOptions.PathParameters.Add("yearId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(yearId)); // path parameter
            if (reference != null)
            {
                localVarRequestOptions.QueryParameters.Add(Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToMultiMap("", "reference", reference));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<FipeResult>("/{vehicleType}/brands/{brandId}/models/{modelId}/years/{yearId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFipeInfo", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Models by brand Returns models for the brand
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <returns>List&lt;NamedCode&gt;</returns>
        public List<NamedCode> GetModelsByBrand(VehiclesType vehicleType, int brandId)
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> localVarResponse = GetModelsByBrandWithHttpInfo(vehicleType, brandId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Models by brand Returns models for the brand
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <returns>ApiResponse of List&lt;NamedCode&gt;</returns>
        public Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> GetModelsByBrandWithHttpInfo(VehiclesType vehicleType, int brandId)
        {
            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("vehicleType", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(vehicleType)); // path parameter
            localVarRequestOptions.PathParameters.Add("brandId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(brandId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<NamedCode>>("/{vehicleType}/brands/{brandId}/models", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetModelsByBrand", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Models by brand Returns models for the brand
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NamedCode&gt;</returns>
        public async System.Threading.Tasks.Task<List<NamedCode>> GetModelsByBrandAsync(VehiclesType vehicleType, int brandId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> localVarResponse = await GetModelsByBrandWithHttpInfoAsync(vehicleType, brandId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Models by brand Returns models for the brand
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NamedCode&gt;)</returns>
        public async System.Threading.Tasks.Task<Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>>> GetModelsByBrandWithHttpInfoAsync(VehiclesType vehicleType, int brandId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("vehicleType", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(vehicleType)); // path parameter
            localVarRequestOptions.PathParameters.Add("brandId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(brandId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<NamedCode>>("/{vehicleType}/brands/{brandId}/models", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetModelsByBrand", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fipe month references Returns months and codes reference from Fipe
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Reference&gt;</returns>
        public List<Reference> GetReferences()
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<List<Reference>> localVarResponse = GetReferencesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fipe month references Returns months and codes reference from Fipe
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Reference&gt;</returns>
        public Br.Com.Parallelum.Fipe.Client.ApiResponse<List<Reference>> GetReferencesWithHttpInfo()
        {
            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Reference>>("/references", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetReferences", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fipe month references Returns months and codes reference from Fipe
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Reference&gt;</returns>
        public async System.Threading.Tasks.Task<List<Reference>> GetReferencesAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<List<Reference>> localVarResponse = await GetReferencesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fipe month references Returns months and codes reference from Fipe
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Reference&gt;)</returns>
        public async System.Threading.Tasks.Task<Br.Com.Parallelum.Fipe.Client.ApiResponse<List<Reference>>> GetReferencesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Reference>>("/references", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetReferences", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Years for model Returns years for the specific model
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <returns>List&lt;NamedCode&gt;</returns>
        public List<NamedCode> GetYearByModel(VehiclesType vehicleType, int brandId, int modelId)
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> localVarResponse = GetYearByModelWithHttpInfo(vehicleType, brandId, modelId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Years for model Returns years for the specific model
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <returns>ApiResponse of List&lt;NamedCode&gt;</returns>
        public Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> GetYearByModelWithHttpInfo(VehiclesType vehicleType, int brandId, int modelId)
        {
            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("vehicleType", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(vehicleType)); // path parameter
            localVarRequestOptions.PathParameters.Add("brandId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(brandId)); // path parameter
            localVarRequestOptions.PathParameters.Add("modelId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(modelId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<NamedCode>>("/{vehicleType}/brands/{brandId}/models/{modelId}/years", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetYearByModel", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Years for model Returns years for the specific model
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NamedCode&gt;</returns>
        public async System.Threading.Tasks.Task<List<NamedCode>> GetYearByModelAsync(VehiclesType vehicleType, int brandId, int modelId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>> localVarResponse = await GetYearByModelWithHttpInfoAsync(vehicleType, brandId, modelId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Years for model Returns years for the specific model
        /// </summary>
        /// <exception cref="Br.Com.Parallelum.Fipe.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="vehicleType">Type of vehicle</param>
        /// <param name="brandId">Brand of the vehicle</param>
        /// <param name="modelId">Model of the vehicle</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NamedCode&gt;)</returns>
        public async System.Threading.Tasks.Task<Br.Com.Parallelum.Fipe.Client.ApiResponse<List<NamedCode>>> GetYearByModelWithHttpInfoAsync(VehiclesType vehicleType, int brandId, int modelId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Br.Com.Parallelum.Fipe.Client.RequestOptions localVarRequestOptions = new Br.Com.Parallelum.Fipe.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Br.Com.Parallelum.Fipe.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("vehicleType", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(vehicleType)); // path parameter
            localVarRequestOptions.PathParameters.Add("brandId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(brandId)); // path parameter
            localVarRequestOptions.PathParameters.Add("modelId", Br.Com.Parallelum.Fipe.Client.ClientUtils.ParameterToString(modelId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<NamedCode>>("/{vehicleType}/brands/{brandId}/models/{modelId}/years", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetYearByModel", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
