/*
 * Fipe API
 *
 * API de Consulta Tabela FIPE fornece preços médios de veículos no mercado nacional. Atualizada mensalmente com dados extraidos da tabela FIPE
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: deividfortuna@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Br.Com.Parallelum.Fipe.Api;
using Br.Com.Parallelum.Fipe.Model;
using Br.Com.Parallelum.Fipe.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Br.Com.Parallelum.Fipe.Test.Model
{
    /// <summary>
    ///  Class for testing FipeResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FipeResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FipeResult
        //private FipeResult instance;

        public FipeResultTests()
        {
            // TODO uncomment below to create an instance of FipeResult
            //instance = new FipeResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FipeResult
        /// </summary>
        [Fact]
        public void FipeResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" FipeResult
            //Assert.IsType<FipeResult>(instance);
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'ModelYear'
        /// </summary>
        [Fact]
        public void ModelYearTest()
        {
            // TODO unit test for the property 'ModelYear'
        }
        /// <summary>
        /// Test the property 'Fuel'
        /// </summary>
        [Fact]
        public void FuelTest()
        {
            // TODO unit test for the property 'Fuel'
        }
        /// <summary>
        /// Test the property 'CodeFipe'
        /// </summary>
        [Fact]
        public void CodeFipeTest()
        {
            // TODO unit test for the property 'CodeFipe'
        }
        /// <summary>
        /// Test the property 'ReferenceMonth'
        /// </summary>
        [Fact]
        public void ReferenceMonthTest()
        {
            // TODO unit test for the property 'ReferenceMonth'
        }
        /// <summary>
        /// Test the property 'VehicleType'
        /// </summary>
        [Fact]
        public void VehicleTypeTest()
        {
            // TODO unit test for the property 'VehicleType'
        }
        /// <summary>
        /// Test the property 'FuelAcronym'
        /// </summary>
        [Fact]
        public void FuelAcronymTest()
        {
            // TODO unit test for the property 'FuelAcronym'
        }

    }

}
