/*
 * Fipe API
 *
 * API de Consulta Tabela FIPE fornece preços médios de veículos no mercado nacional. Atualizada mensalmente com dados extraidos da tabela FIPE
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: deividfortuna@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Br.Com.Parallelum.Fipe.Api;
using Br.Com.Parallelum.Fipe.Model;
using Br.Com.Parallelum.Fipe.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Br.Com.Parallelum.Fipe.Test.Model
{
    /// <summary>
    ///  Class for testing Reference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Reference
        //private Reference instance;

        public ReferenceTests()
        {
            // TODO uncomment below to create an instance of Reference
            //instance = new Reference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Reference
        /// </summary>
        [Fact]
        public void ReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Reference
            //Assert.IsType<Reference>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }

    }

}
