/*
 * Fipe API
 *
 * API de Consulta Tabela FIPE fornece preços médios de veículos no mercado nacional. Atualizada mensalmente com dados extraidos da tabela FIPE
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: deividfortuna@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Br.Com.Parallelum.Fipe.Api;
using Br.Com.Parallelum.Fipe.Model;
using Br.Com.Parallelum.Fipe.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Br.Com.Parallelum.Fipe.Test.Model
{
    /// <summary>
    ///  Class for testing VehiclesType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VehiclesTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VehiclesType
        //private VehiclesType instance;

        public VehiclesTypeTests()
        {
            // TODO uncomment below to create an instance of VehiclesType
            //instance = new VehiclesType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VehiclesType
        /// </summary>
        [Fact]
        public void VehiclesTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" VehiclesType
            //Assert.IsType<VehiclesType>(instance);
        }



    }

}
